version: '3.8'
services:
 code_agent_server:
   build: .
   image: winshare/ele.ink:cn.cuda117.torch201.paddle251.nltk.codeagent.240327
   ports:
     - "10010:10010"
   volumes:
     - /workspace:/workspace
     - /data:/data
     - /data/agent:/data/agent  # 请替换为实际clone代码的路径
   deploy:
     resources:
       reservations:
         devices:
           - driver: nvidia
             count: 1
             capabilities: [gpu]
   command: zsh -c "git clone https://github.com/ceresman/code_agent_server.git" && "cd code_agent_server" && "uvicorn server:app --reload --host 0.0.0.0 --port 10010"
